# Generated by Django 3.2.15 on 2022-08-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=25)),
                ('floorlvl', models.CharField(max_length=25, verbose_name='Floor Level')),
                ('dorm_name', models.CharField(choices=[('Male Dorm', 'Male Dorm'), ('Female Dorm', 'Female Dorm')], max_length=25)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
