# Generated by Django 4.1 on 2022-08-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=100)),
                ('is_offered', models.CharField(default='1', editable=False, max_length=5)),
                ('base_amount', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
