# Generated by Django 4.1 on 2022-08-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.CharField(max_length=25)),
                ('bed_no', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Beds',
            },
        ),
    ]
