# Generated by Django 4.1 on 2022-08-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('psu_email', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('security_question', models.CharField(max_length=250)),
                ('security_answer', models.CharField(max_length=250)),
                ('recovery_email', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
