# Generated by Django 4.1 on 2022-08-30 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_alter_user_security_question_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.bed')),
            ],
            options={
                'verbose_name_plural': 'Bed Price History',
            },
        ),
    ]
