# Generated by Django 4.1 on 2022-08-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0006_bedpricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
