# Generated by Django 4.1 on 2022-08-31 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0007_alter_service_base_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.bed')),
                ('bedPrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.bedpricehistory')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.person')),
            ],
            options={
                'verbose_name_plural': 'Occupants',
            },
        ),
    ]
