# Generated by Django 4.1 on 2022-08-31 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0009_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.bill')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.service')),
            ],
            options={
                'verbose_name_plural': 'Bill Details',
            },
        ),
    ]
