# Generated by Django 4.1 on 2022-08-31 04:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0010_bill_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('receipt_no', models.CharField(max_length=250)),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.occupant')),
            ],
            options={
                'verbose_name_plural': 'Payment',
            },
        ),
    ]
