# Generated by Django 3.2.15 on 2022-09-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(default='vacant', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
