# Generated by Django 3.2.15 on 2022-09-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0012_auto_20220928_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_status',
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_status',
            field=models.CharField(default='vacant', max_length=25, verbose_name='Status'),
        ),
    ]
