# Generated by Django 3.2.15 on 2022-09-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0013_auto_20220928_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_offered',
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=25),
        ),
    ]
