# Generated by Django 3.2.15 on 2022-09-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0014_auto_20220929_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=25),
        ),
    ]
