# Generated by Django 3.2.15 on 2022-09-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0015_alter_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='psu_email',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='none', max_length=250, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='Puerto Princesa City', max_length=250, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(default='Philippines', max_length=250, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='person',
            name='municipality',
            field=models.CharField(default='none', max_length=250, verbose_name='municipality'),
        ),
        migrations.AddField(
            model_name='person',
            name='province',
            field=models.CharField(default='Palawan', max_length=250, verbose_name='province'),
        ),
        migrations.AddField(
            model_name='person',
            name='psu_email',
            field=models.CharField(default='none', max_length=250, verbose_name='psu_email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Gay', 'Gay'), ('Lesbian', 'Lesbian'), ('Transgender', 'Transgender'), ('Rather not to say', 'Rather not to say')], max_length=50),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=250)),
                ('present_address', models.CharField(max_length=250)),
                ('contact_no', models.CharField(max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.person')),
            ],
            options={
                'verbose_name_plural': 'Guardians',
            },
        ),
    ]
