# Generated by Django 3.2.15 on 2022-09-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0016_auto_20220930_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='person',
        ),
        migrations.AddField(
            model_name='guardian',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dormitory.user'),
        ),
        migrations.AddField(
            model_name='person',
            name='guardian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dormitory.guardian'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Gay', 'Gay'), ('Lesbian', 'Lesbian'), ('Transgender', 'Transgender')], max_length=50),
        ),
    ]
