# Generated by Django 3.2.15 on 2022-09-30 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0017_auto_20220930_1511'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='guardian',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.user'),
        # ),
        # migrations.AlterField(
        #     model_name='person',
        #     name='guardian',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.guardian'),
        # ),
    ]
