# Generated by Django 3.2.15 on 2022-10-04 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0022_auto_20221002_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dormitory.room'),
            preserve_default=False,
        ),
    ]
