# Generated by Django 3.2.15 on 2022-10-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0023_auto_20221004_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_contact_no',
            field=models.CharField(default='none', max_length=20, verbose_name="Guardian's contact number"),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_email_address',
            field=models.CharField(default='none', max_length=250, verbose_name="Guardian's email"),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_first_name',
            field=models.CharField(default='none', max_length=250, verbose_name="Guardian's First name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_last_name',
            field=models.CharField(default='none', max_length=250, verbose_name="Guardian's Last name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_present_address',
            field=models.CharField(default='none', max_length=250, verbose_name="Guardian's address"),
        ),
        migrations.AlterField(
            model_name='person',
            name='office_dept',
            field=models.CharField(choices=[('Computer Studies Department', 'Computer Studies Department'), ('Math Department', 'Math Department'), ('Science Department', 'Science Department'), ('Physical Education Department', 'Physical Education Department')], max_length=250, verbose_name='Office / Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='psu_email',
            field=models.CharField(default='none', max_length=250, verbose_name='PSU Email'),
        ),
    ]
