# Generated by Django 3.2.15 on 2022-10-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0024_auto_20221004_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='none', max_length=250, null=True),
        ),
    ]
