# Generated by Django 3.2.15 on 2022-10-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0025_alter_person_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='bedPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
