# Generated by Django 3.2.15 on 2022-10-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0028_auto_20221004_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_details',
            name='occupant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.occupant'),
        ),
    ]
