# Generated by Django 3.2.15 on 2022-10-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0030_alter_bill_details_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Field1',
            field=models.BooleanField(default=False, verbose_name='Two pieces 2x2 coloured ID pictures taken not more than six months prior to the signing of the contract'),
        ),
        migrations.AddField(
            model_name='person',
            name='Field2',
            field=models.BooleanField(default=False, verbose_name='Medical Certificate from the University physician'),
        ),
        migrations.AddField(
            model_name='person',
            name='Field3',
            field=models.BooleanField(default=False, verbose_name='Fully accomplished application form (form OIA-OID)'),
        ),
        migrations.AddField(
            model_name='person',
            name='Field4',
            field=models.BooleanField(default=False, verbose_name='Special power of attorney (SPA) for guardian'),
        ),
        migrations.AddField(
            model_name='person',
            name='Field5',
            field=models.BooleanField(default=False, verbose_name='Photocopy of the University Identification card valid on the school year enrolled'),
        ),
        migrations.AddField(
            model_name='person',
            name='Field6',
            field=models.BooleanField(default=False, verbose_name='Certificate of Enrollment'),
        ),
        migrations.AddField(
            model_name='person',
            name='Field7',
            field=models.BooleanField(default=False, verbose_name='Photocopy of the dormitory ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_contact_no',
            field=models.CharField(default='none', max_length=20, verbose_name="Guardian's Contact Number"),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_email_address',
            field=models.CharField(default='none', max_length=250, verbose_name="Guardian's Email"),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_present_address',
            field=models.CharField(default='none', max_length=250, verbose_name="Guardian's Address"),
        ),
    ]
