# Generated by Django 3.2.15 on 2022-10-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0031_auto_20221006_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Field1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field7',
            field=models.BooleanField(default=False),
        ),
    ]
