# Generated by Django 3.2.15 on 2022-10-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0032_auto_20221006_2205'),
        ('dormitory', '0032_auto_20221006_2212'),
    ]

    operations = [
    ]
