# Generated by Django 3.2.15 on 2022-10-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0033_merge_0032_auto_20221006_2205_0032_auto_20221006_2212'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='bed',
        #     name='bed_no',
        # ),
        migrations.AddField(
            model_name='bed',
            name='bed_code',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_status',
            field=models.CharField(default='Vacant', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field1',
            field=models.BooleanField(default=False, verbose_name='Two pieces 2"x2" coloured ID pictures taken not more than six months prior to the signing of the contract'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field2',
            field=models.BooleanField(default=False, verbose_name='Medical Certificate from the University physician'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field3',
            field=models.BooleanField(default=False, verbose_name='Fully accomplished application form (form OIA-OID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field4',
            field=models.BooleanField(default=False, verbose_name='Special power of attorney (SPA) for guardian'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field5',
            field=models.BooleanField(default=False, verbose_name='Photocopy of the University Identification card valid on the school year enrolled'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field6',
            field=models.BooleanField(default=False, verbose_name='Certificate of Enrollment'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Field7',
            field=models.BooleanField(default=False, verbose_name='Photocopy of the dormitory ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='dorm_name',
            field=models.CharField(choices=[('Male Dorm', 'Male Dorm'), ('Female Dorm', 'Female Dorm'), ('Foreign Dorm', 'Foreign Dorm')], max_length=25),
        ),
    ]
