# Generated by Django 3.2.15 on 2022-10-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0034_auto_20221012_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='bedPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
