# Generated by Django 3.2.15 on 2022-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0035_alter_occupant_bedprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=6),
        ),
    ]
