# Generated by Django 3.2.15 on 2022-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0035_alter_bed_bed_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='bed_no',
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_code',
            field=models.CharField(max_length=25),
        ),
    ]
