# Generated by Django 3.2.15 on 2022-10-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0040_alter_bed_bed_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='bed_code',
        ),
    ]
