# Generated by Django 3.2.15 on 2022-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0041_remove_bed_bed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_code',
            field=models.CharField(default='none', max_length=25, verbose_name='Bed Code'),
        ),
    ]
