# Generated by Django 3.2.15 on 2022-10-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0042_bed_bed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
