# Generated by Django 3.2.15 on 2022-10-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0043_alter_bed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
