# Generated by Django 3.2.15 on 2022-10-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0036_alter_bed_price'),
        ('dormitory', '0044_alter_bed_price'),
    ]

    operations = [
    ]
