# Generated by Django 3.2.15 on 2022-10-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0036_alter_bed_price'),
        ('dormitory', '0045_alter_person_gender'),
    ]

    operations = [
    ]
