# Generated by Django 3.2.15 on 2022-10-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0047_alter_bed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floorlvl',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=25, verbose_name='Floor Level'),
        ),
    ]
