# Generated by Django 3.2.15 on 2022-10-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0048_alter_room_floorlvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('LGBTQIA+', 'LGBTQIA+')], max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='office_dept',
            field=models.CharField(choices=[('Electrical Engineering Department', 'Electrical Engineering Department'), ('Computer Studies Department', 'Computer Studies Department'), ('Department of Physical Education', 'Department of Physical Education'), ('Department of Secondary Education', 'Department of Secondary Education'), ('Bio-Physical Science Department', 'Bio-Physical Science Department'), ('Architecture Department', 'Architecture Department'), ('Civil Engineering Department', 'Civil Engineering Department'), ('Department of Elementary Education', 'Department of Elementary Education'), ('Petroleum Engineering Department', 'Petroleum Engineering Department'), ('Dapartment of Secondary Education', 'Dapartment of Secondary Education'), ('Mechanical Engineering Department', 'Mechanical Engineering Department'), ('Not yet included', 'Not yet included')], max_length=250, verbose_name='Office / Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='program',
            field=models.CharField(choices=[('BAMC', 'BAMC'), ('BSEE', 'BSEE'), ('BSTM', 'BSTM'), ('BSA', 'BSA'), ('BSIT', 'BSIT'), ('BSN', 'BSN'), ('BPED', 'BPED'), ('BSCrim', 'BSCrim'), ('BSED-3', 'BSED-3'), ('BSM', 'BSM'), ('BSMB', 'BSMB'), ('BSBA-ECO', 'BSBA-ECO'), ('BSHM', 'BSHM'), ('BSAr', 'BSAr'), ('BSP', 'BSP'), ('BAPolSci', 'BAPolSci'), ('BSCE', 'BSCE'), ('BSTM', 'BSTM'), ('BSPA', 'BSPA'), ('BSCS', 'BSCS'), ('DM', 'DM'), ('BEED', 'BEED'), ('BSED-2', 'BSED-2'), ('BSSW', 'BSSW'), ('BSPE', 'BSPE'), ('BSBA-FM', 'BSBA-FM'), ('BSB-MB', 'BSB-MB'), ('BSED-1', 'BSED-1'), ('BAPS', 'BAPS'), ('BSME', 'BSME'), ('BSBA-MM', 'BSBA-MM'), ('BSMA', 'BSMA'), ('BSES', 'BSES'), ('BSE', 'BSE'), ('BSBA-HRDM', 'BSBA-HRDM'), ('BSB-MD', 'BSB-MD')], max_length=250),
        ),
    ]
