# Generated by Django 3.2.15 on 2022-10-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0049_auto_20221020_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Under Maint.', 'Under Maint.')], default='Vacant', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='municipality',
            field=models.CharField(choices=[('None', 'None'), ('Aborlan', 'Aborlan'), ('Agutaya', 'Agutaya'), ('Araceli', 'Araceli'), ('Balabac', 'Balabac'), ('Batazar', 'Batazar'), ('Brookes Point', 'Brookes Point'), ('Busuanga', 'Busuanga'), ('Cagayancillo', 'Cagayancillo'), ('Coron', 'Coron'), ('Culion', 'Culion'), ('Cuyo', 'Cuyo'), ('Dumaran', 'Dumaran'), ('El Nido', 'El Nido'), ('Iwahig Penal Colony', 'Iwahig Penal Colony'), ('Kalayaan', 'Kalayaan'), ('Linapacan', 'Linapacan'), ('Magsaysay', 'Magsaysay'), ('Narra', 'Narra'), ('Puerto Princesa City', 'Puerto Princesa City'), ('Aborlan', 'Aborlan'), ('Quezon', 'Quezon'), ('Roxas', 'Roxas'), ('Rizal', 'Rizal'), ('San Vicente', 'San Vicente'), ('Sofronio Española', 'Sofronio Española'), ('Taytay', 'Taytay')], default='None', max_length=250, verbose_name='municipality'),
        ),
    ]
