# Generated by Django 3.2.15 on 2022-10-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0045_merge_0036_alter_bed_price_0044_alter_bed_price'),
        ('dormitory', '0050_auto_20221024_1348'),
    ]

    operations = [
    ]
