# Generated by Django 3.2.15 on 2022-11-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0051_merge_20221031_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reg_status',
            field=models.CharField(default='', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(default='None', max_length=250, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_no',
            field=models.CharField(default='None', max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(default='Philippines', max_length=250, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_contact_no',
            field=models.CharField(default='None', max_length=20, verbose_name="Guardian's Contact Number"),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_email_address',
            field=models.EmailField(default='None', max_length=250, verbose_name="Guardian's Email"),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_first_name',
            field=models.CharField(default='None', max_length=250, verbose_name="Guardian's First name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_last_name',
            field=models.CharField(default='None', max_length=250, verbose_name="Guardian's Last name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_present_address',
            field=models.CharField(default='None', max_length=250, verbose_name="Guardian's Address"),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='municipality',
            field=models.CharField(choices=[('None', 'None'), ('Aborlan', 'Aborlan'), ('Agutaya', 'Agutaya'), ('Araceli', 'Araceli'), ('Balabac', 'Balabac'), ('Batazar', 'Batazar'), ('Brookes Point', 'Brookes Point'), ('Busuanga', 'Busuanga'), ('Cagayancillo', 'Cagayancillo'), ('Coron', 'Coron'), ('Culion', 'Culion'), ('Cuyo', 'Cuyo'), ('Dumaran', 'Dumaran'), ('El Nido', 'El Nido'), ('Iwahig Penal Colony', 'Iwahig Penal Colony'), ('Kalayaan', 'Kalayaan'), ('Linapacan', 'Linapacan'), ('Magsaysay', 'Magsaysay'), ('Narra', 'Narra'), ('Puerto Princesa City', 'Puerto Princesa City'), ('Aborlan', 'Aborlan'), ('Quezon', 'Quezon'), ('Roxas', 'Roxas'), ('Rizal', 'Rizal'), ('San Vicente', 'San Vicente'), ('Sofronio Española', 'Sofronio Española'), ('Taytay', 'Taytay')], default='None', max_length=250, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=models.CharField(default='Palawan', max_length=250, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='person',
            name='psu_email',
            field=models.EmailField(default='None', max_length=250, verbose_name='PSU Email'),
        ),
    ]
