# Generated by Django 3.2.15 on 2022-11-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0052_auto_20221101_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='reg_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Status'),
        ),
    ]
