# Generated by Django 3.2.15 on 2022-11-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0054_alter_person_reg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='reg_status',
        ),
    ]
