# Generated by Django 3.2.15 on 2022-11-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0057_auto_20221104_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_description',
            field=models.CharField(default='none', max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='price',
            field=models.DecimalField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Under Maint.', 'Under Maint.')], decimal_places=0, default=0, max_digits=6),
        ),
    ]
