# Generated by Django 3.2.15 on 2022-11-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0059_auto_20221114_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_details',
            name='quantity',
            field=models.CharField(default='0', max_length=5, verbose_name='Quantity'),
        ),
    ]
