# Generated by Django 3.2.15 on 2022-11-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0061_remove_bill_details_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_details',
            name='quantity',
            field=models.CharField(default='0', max_length=5, verbose_name='Quantity'),
        ),
    ]
