# Generated by Django 3.2.15 on 2022-11-18 04:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dormitory.models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0062_bill_details_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dormitory.bill_details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_code',
            field=models.CharField(default='', max_length=25, verbose_name='Bed Code'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_description',
            field=models.CharField(default='', max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bill_details',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='end_date',
            field=models.DateTimeField(blank=True, default=dormitory.models.one_month_from_today, null=True),
        ),
    ]
