# Generated by Django 3.2.15 on 2022-11-21 12:53

from django.db import migrations, models
import dormitory.models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0064_alter_occupant_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='end_date',
            field=models.DateTimeField(blank=True, default=dormitory.models.one_month_from_today, null=True),
        ),
    ]
