# Generated by Django 3.2.15 on 2022-11-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0066_auto_20221124_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demerit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demerit_name', models.TextField(choices=[('Transfer to other rooms without permission', 'Transfer to other rooms without permission.'), ('Doing malicious conduct on dormitory premises', 'Doing malicious conduct on dormitory premises.'), ('Allowing opposite sex other than the parents to enter his/her room', 'Allowing opposite sex other than the parents to enter his/her room.'), ('Possessing inside the dormitory any firearm, bladed weapon, or any kind of dangerous and deadly weapon; Provided, that this shall not possess the in connection with their studies and have a permit for the purpose.', 'Possessing inside the dormitory any firearm, bladed weapon, or any kind of dangerous and deadly weapon; Provided, that this shall not possess the in connection with their studies and have a permit for the purpose.'), ('Oral defamation against co-residents.', 'Oral defamation against co-residents.'), ('Bullying.', 'Bullying.'), ('Threatening or any attempt to any member of the dormitory with physical harm; unlawfully preventing or threatening the dormitory residents or other dormitory officials to enter the dormitory premises.', 'Threatening or any attempt to any member of the dormitory with physical harm; unlawfully preventing or threatening the dormitory residents or other dormitory officials to enter the dormitory premises.'), ('Non---Securing of Dormitory forms i.e. curfew extension and renewal/clearance forms.', 'Non---Securing of Dormitory forms i.e. curfew extension and renewal/clearance forms.'), ('Non---Compliance related to room checking procedures.', 'Non---Compliance related to room checking procedures.'), ('Non---Compliance to the administrative and dormitory superintendents.', 'Non---Compliance to the administrative and dormitory superintendents.'), ('Bringing of appliances without the approval of the dormitory parent.', 'Bringing of appliances without the approval of the dormitory parent.'), ('Laundering of clothes inside the dormitory.', 'Laundering of clothes inside the dormitory.'), ('Use electrical appliances, including ironing of clothes inside the dormitory.', 'Use electrical appliances, including ironing of clothes inside the dormitory.'), ('Returning after curfew hour or very late from time in indicated on the curfew extension form.', 'Returning after curfew hour or very late from time in indicated on the curfew extension form.'), ('Lending dormitory ID to the outsider and co-residents to enter the dormitory premises.', 'Lending dormitory ID to the outsider and co-residents to enter the dormitory premises.'), ('Using other personal things without permission to the owner.', 'Using other personal things without permission to the owner.'), ('Failure to do proper waste segregation and or throwing garbage in improper places.', 'Failure to do proper waste segregation and or throwing garbage in improper places.'), ('Disturbing / Disrespect on the privacy of others including making noise after curfew hours and playing loud music inside the dormitory.', 'Disturbing / Disrespect on the privacy of others including making noise after curfew hours and playing loud music inside the dormitory.'), ('Vandalism.', 'Vandalism.'), ('Failure to register in logbook.', 'Failure to register in logbook.'), ('Not turning off the fan, aircon, lights and faucet.', 'Not turning off the fan, aircon, lights and faucet.'), ('Shouting and making nuisance inside the dormitory.', 'Shouting and making nuisance inside the dormitory.'), ('Bringing pets in the dormitory.', 'Bringing pets in the dormitory.'), ('Walking around beyond time limits (11:00 PM only).', 'Walking around beyond time limits (11:00 PM only).')], max_length=500)),
                ('demerit_points', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=2)),
                ('demerit_description', models.TextField(default='None', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Demerits',
            },
        ),
        migrations.AlterField(
            model_name='bill_details',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
