# Generated by Django 3.2.15 on 2022-11-28 03:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0069_alter_demerit_demerit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupant_Demerit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cur_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(default='None', max_length=500)),
                ('demerit_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.demerit')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.occupant')),
            ],
            options={
                'verbose_name_plural': 'Occupant Demerits',
            },
        ),
    ]
