# Generated by Django 3.2.15 on 2022-11-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0070_occupant_demerit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occupant_Demerit',
            new_name='OccupantDemerit',
        ),
    ]
