# Generated by Django 3.2.15 on 2022-12-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0072_auto_20221208_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(blank=True, default='active', max_length=20, null=True),
        ),
    ]
