# Generated by Django 3.2.15 on 2022-12-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0073_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(blank=True, default='inactive', max_length=20, null=True),
        ),
    ]
