# Generated by Django 3.2.15 on 2022-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0074_alter_user_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
