# Generated by Django 3.2.15 on 2022-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0075_user_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=20, null=True),
        ),
    ]
