# Generated by Django 3.2.15 on 2023-01-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0082_auto_20230102_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
