# Generated by Django 3.2.15 on 2023-01-05 03:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0084_alter_person_office_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_class',
            field=models.CharField(blank=True, choices=[('Front Desk', 'Front Desk'), ('Accounting Staff', 'Accounting Staff'), ('Super Administrator', 'Super Administrator'), ('Dorm Manager', 'Dorm Manager')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bill_details',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='bill_details',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='program',
            field=models.CharField(choices=[('Bachelor of Science in Social Work', 'Bachelor of Science in Social Work'), ('Bachelor of Science in Psychology', 'Bachelor of Science in Psychology'), ('Bachelor of Arts in Communication', 'Bachelor of Arts in Communication'), ('Bachelor of Arts in Political Science', 'Bachelor of Arts in Political Science'), ('Bachelor of Arts in Philippine Studies', 'Bachelor of Arts in Philippine Studies'), ('Bachelor of Science in Biology Major in Medical Biology', 'Bachelor of Science in Biology Major in Medical Biology'), ('Bachelor of Science in Marine Biology', 'Bachelor of Science in Marine Biology'), ('Bachelor of Science in Environmental Science', 'Bachelor of Science in Environmental Science'), ('Bachelor of Science in Information Technology', 'Bachelor of Science in Information Technology'), ('Bachelor of Science in Computer Science', 'Bachelor of Science in Computer Science'), ('Bachelor of Science in Physical Education', 'Bachelor of Science in Physical Education'), ('Bachelor of Science in Elementary Education', 'Bachelor of Science in Elementary Education'), ('Bachelor of Science in Secondary Education Major in Science', 'Bachelor of Science in Secondary Education Major in Science'), ('Bachelor of Science in Secondary Education Major in Math', 'Bachelor of Science in Secondary Education Major in Math'), ('Bachelor of Science in Secondary Education Major in English', 'Bachelor of Science in Secondary Education Major in English'), ('Bachelor of Science in Secondary Education Major in Filipino', 'Bachelor of Science in Secondary Education Major in Filipino'), ('Bachelor of Science in Secondary Education Major in Social Studies', 'Bachelor of Science in Secondary Education Major in Social Studies'), ('Bachelor of Science in Secondary Education Major in Values', 'Bachelor of Science in Secondary Education Major in Values'), ('Bachelor of Science in Accountancy', 'Bachelor of Science in Accountancy'), ('Bachelor of Science in Management Accountancy', 'Bachelor of Science in Management Accountancy'), ('Bachelor of Science in Entrepreneurship', 'Bachelor of Science in Entrepreneurship'), ('Bachelor of Science in Business Administration  Major in Marketing Management', 'Bachelor of Science in Business Administration  Major in Marketing Management'), ('Bachelor of Science in Business Administration  Major in Human Resource Management', 'Bachelor of Science in Business Administration  Major in Human Resource Management'), ('Bachelor of Science in Hospitality Management', 'Bachelor of Science in Hospitality Management'), ('Track - Culinary Arts and Kitchen Management', 'Track - Culinary Arts and Kitchen Management'), ('Bachelor of Science in Tourism Management', 'Bachelor of Science in Tourism Management'), ('Track - Hotel,Resort, and Club Management', 'Track - Hotel,Resort, and Club Management'), ('Bachelor of Science in Civil Engineering', 'Bachelor of Science in Civil Engineering'), ('Bachelor of Science in Mechanical Engineering', 'Bachelor of Science in Mechanical Engineering'), ('Bachelor of Science in Electrical Engineering', 'Bachelor of Science in Electrical Engineering'), ('Bachelor of Science in Petroleum Engineering', 'Bachelor of Science in Petroleum Engineering'), ('Bachelor of Science in Architecture', 'Bachelor of Science in Architecture'), ('Bachelor of Science in Nursing', 'Bachelor of Science in Nursing'), ('Diploma in Midwifery', 'Diploma in Midwifery'), ('Bachelor of Science in Midwifery', 'Bachelor of Science in Midwifery'), ('Bachelor of Science in Criminology', 'Bachelor of Science in Criminology')], max_length=250),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.user')),
            ],
        ),
    ]
