# Generated by Django 3.2.15 on 2023-01-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0085_auto_20230105_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
