# Generated by Django 3.2.15 on 2023-01-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0086_delete_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demerit',
            name='demerit_points',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
    ]
