# Generated by Django 3.2.15 on 2023-04-03 08:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0087_alter_demerit_demerit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
