# Generated by Django 3.2.15 on 2023-04-05 16:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0088_alter_person_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='guardian_contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='municipality',
            field=models.CharField(choices=[('None', 'None'), ('Aborlan', 'Aborlan'), ('Agutaya', 'Agutaya'), ('Araceli', 'Araceli'), ('Balabac', 'Balabac'), ('Batazar', 'Batazar'), ('Brookes Point', 'Brookes Point'), ('Busuanga', 'Busuanga'), ('Cagayancillo', 'Cagayancillo'), ('Coron', 'Coron'), ('Culion', 'Culion'), ('Cuyo', 'Cuyo'), ('Dumaran', 'Dumaran'), ('El Nido', 'El Nido'), ('Iwahig Penal Colony', 'Iwahig Penal Colony'), ('Kalayaan', 'Kalayaan'), ('Linapacan', 'Linapacan'), ('Magsaysay', 'Magsaysay'), ('Narra', 'Narra'), ('Puerto Princesa City', 'Puerto Princesa City'), ('Quezon', 'Quezon'), ('Roxas', 'Roxas'), ('Rizal', 'Rizal'), ('San Vicente', 'San Vicente'), ('Sofronio Española', 'Sofronio Española'), ('Taytay', 'Taytay')], default='None', max_length=250, verbose_name='Municipality'),
        ),
    ]
