# Generated by Django 3.2.15 on 2023-04-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0090_auto_20230406_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_details',
            name='description',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='bill_details',
            name='occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dormitory.occupant'),
        ),
    ]
