# Generated by Django 3.2.15 on 2023-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0092_auto_20230422_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_let_ref',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
