# Generated by Django 3.2.15 on 2023-05-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0093_payment_pay_let_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.CharField(default='', max_length=250, verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='', max_length=300, verbose_name='Title'),
        ),
    ]
