# Generated by Django 3.2.15 on 2023-05-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0094_auto_20230520_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=300, verbose_name='Description'),
        ),
    ]
