# Generated by Django 3.2.15 on 2023-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0095_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='None', max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.CharField(default='None', max_length=250, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='None', max_length=300, verbose_name='Title'),
        ),
    ]
